apiVersion: v1
kind: Service
metadata:
  name: saleshistory-service
spec:
  selector:
    app: classicbusinessmodel-app
  ports:
    - protocol: TCP
      port: 8978
      targetPort: 8978
  type: LoadBalancer